version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  fetch_digest_and_email:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout

      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt

      - run:
          name: Install additional dependencies
          command: |
            pip install requests google-generativeai bs4 feedparser
            pip install -q -U "google-genai>=1.0.0"
            pip install python-dotenv

      - run:
          name: Run fetch script
          command: python fetch_keyword_stock_circl_news.py

      - run:
          name: Run text process script
          command: python text_process.py

      - run:
          name: Run send script
          command: python send_to_gemini_circle.py

  build-and-test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout

      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt

      - run:
          name: Install additional dependencies
          command: |
            pip install requests google-generativeai bs4 feedparser
            pip install -q -U "google-genai>=1.0.0"

      - run:
          name: Run fetch script
          command: python fetch_keyword_stock_news.py

      - run:
          name: Run text process script
          command: python text_process.py

      - run:
          name: Run send script
          command: python send_to_gemini_news.py


      - store_test_results:
          path: test-results

      - store_artifacts:
          path: coverage.xml
workflows:
  send_digest_every_3_hours:
    jobs:
      - fetch_digest_and_email:
          filters:
            branches:
              only:
                - main

  build-and-test-workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - main
