version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  fetch_digest_and_email:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run:
          name: Install additional dependencies
          command: |
            pip install requests google-generativeai bs4 feedparser
      - run:
          name: Run fetch script
          command: python fetch_keyword_stock_news.py
      - run:
          name: Run text process script
          command: python text_process.py
      - run:
          name: Run send script
          command: python send_to_gemini_news.py
          environment:
            GEMINI_API_KEY: $GEMINI_API_KEY
            EMAIL_USER: $EMAIL_USER
            EMAIL_PASS: $EMAIL_PASS
            EMAIL_TO: $EMAIL_TO

  build-and-test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run:
          name: Install additional dependencies
          command: |
            pip install requests google-generativeai bs4 feedparser
      - run:
          name: Run fetch script
          command: python fetch_keyword_stock_news.py
      - run:
          name: Run text process script
          command: python text_process.py
      - run:
          name: Run send script
          command: python send_to_gemini_news.py
          environment:
            GEMINI_API_KEY: $GEMINI_API_KEY
            EMAIL_USER: $EMAIL_USER
            EMAIL_PASS: $EMAIL_PASS
            EMAIL_TO: $EMAIL_TO
      - run:
          name: Run tests (optional)
          command: |
            pip install pytest pytest-cov requests-mock
            if [ -d "tests" ]; then
              pytest --cov=./ --cov-report=xml tests/ || true
            else
              echo "No tests directory found, skipping tests"
            fi
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: coverage.xml

workflows:
  send_digest_every_3_hours:
    triggers:
      - schedule:
          cron: "0 0,3,6,9,12,15,18,21 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - fetch_digest_and_email

  build-and-test-workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - main
