name: Capture Twitter Screenshots

on:
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libnss3 libxss1 libasound2 libgtk-3-0
        pip install playwright
        playwright install chromium

    - name: Run Playwright screenshot script
      run: |
        xvfb-run --auto-servernum --server-args='-screen 0 1280x720x24' python downnn.py
