name: Fetch Groww Digest and Email Analysis

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: "30 12 * * *" # Runs daily at 12:30 PM UTC (6:00 PM IST)

jobs:
  fetch_digest_and_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install requests google-generativeai
        pip install -q -U "google-genai>=1.0.0
        

    - name: Run Groww Digest Analysis Script
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
      run: python gooorow_digest.py
